// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://hgstyhpuewxeiwpphorj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhnc3R5aHB1ZXd4ZWl3cHBob3JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNjMxOTMsImV4cCI6MjA3MjczOTE5M30.7ivHc1zvO4RfMQ-V0MGLraZcT_XGyjds0-qqxHS2YBU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);